// Code generated by sql2gql. DO NOT EDIT.

package rlts

import (
	"context"

	"github.com/google/wire"
	"github.com/ketan-10/sql2gql/examples/pokemon/internal"
	"github.com/ketan-10/sql2gql/examples/pokemon/sql2gql/repo"
	"github.com/ketan-10/sql2gql/examples/pokemon/sql2gql/table"
)

type IPokemonTypesRltsRepository interface {

	// This Table Pointing to Other Table!!!, ManyToOne <- As Many records from other table can point to this table one record
	PokemonByPokemonID(ctx context.Context, obj *table.PokemonTypes, filter *table.PokemonFilter) (*table.Pokemon, error)
	TypesByTypeID(ctx context.Context, obj *table.PokemonTypes, filter *table.TypesFilter) (*table.Types, error)

	//  Other Table Pointing to This Table!!!, OneToMany <- As This Table record can point to Multiple Other table record

}

type PokemonTypesRltsRepository struct {
	PokemonRepository repo.IPokemonRepository

	TypesRepository repo.ITypesRepository
}

var NewPokemonTypesRltsRepository = wire.NewSet(
	wire.Struct(new(PokemonTypesRltsRepository), "*"),
	wire.Bind(new(IPokemonTypesRltsRepository), new(*PokemonTypesRltsRepository)),
)

func (ptr *PokemonTypesRltsRepository) PokemonByPokemonID(ctx context.Context, obj *table.PokemonTypes, filter *table.PokemonFilter) (*table.Pokemon, error) {
	if obj == nil {
		return nil, nil
	}

	if filter == nil {
		filter = &table.PokemonFilter{}
	}

	filter.AddID(internal.Eq, obj.PokemonID)
	result, err := ptr.PokemonRepository.FindAllPokemon(ctx, filter, nil)

	if err != nil {
		return nil, err
	}

	if result.TotalCount == 0 {
		return nil, nil
	}
	return &result.Data[0], nil
}
func (ptr *PokemonTypesRltsRepository) TypesByTypeID(ctx context.Context, obj *table.PokemonTypes, filter *table.TypesFilter) (*table.Types, error) {
	if obj == nil {
		return nil, nil
	}

	if filter == nil {
		filter = &table.TypesFilter{}
	}

	filter.AddID(internal.Eq, obj.TypeID)
	result, err := ptr.TypesRepository.FindAllTypes(ctx, filter, nil)

	if err != nil {
		return nil, err
	}

	if result.TotalCount == 0 {
		return nil, nil
	}
	return &result.Data[0], nil
}
