// Code generated by sql2gql. DO NOT EDIT.

package rlts

import (
	"context"

	"github.com/google/wire"
	"github.com/ketan-10/sql2gql/examples/pokemon/internal"
	"github.com/ketan-10/sql2gql/examples/pokemon/sql2gql/repo"
	"github.com/ketan-10/sql2gql/examples/pokemon/sql2gql/table"
)

type IPokemonAbilitiesRltsRepository interface {

	// This Table Pointing to Other Table!!!, ManyToOne <- As Many records from other table can point to this table one record
	PokemonByFkPokemon(ctx context.Context, obj *table.PokemonAbilities, filter *table.PokemonFilter) (*table.Pokemon, error)
	AbilitiesByFkAbility(ctx context.Context, obj *table.PokemonAbilities, filter *table.AbilitiesFilter) (*table.Abilities, error)

	//  Other Table Pointing to This Table!!!, OneToMany <- As This Table record can point to Multiple Other table record

}

type PokemonAbilitiesRltsRepository struct {
	PokemonRepository repo.IPokemonRepository

	AbilitiesRepository repo.IAbilitiesRepository
}

var NewPokemonAbilitiesRltsRepository = wire.NewSet(
	wire.Struct(new(PokemonAbilitiesRltsRepository), "*"),
	wire.Bind(new(IPokemonAbilitiesRltsRepository), new(*PokemonAbilitiesRltsRepository)),
)

func (par *PokemonAbilitiesRltsRepository) PokemonByFkPokemon(ctx context.Context, obj *table.PokemonAbilities, filter *table.PokemonFilter) (*table.Pokemon, error) {
	if obj == nil {
		return nil, nil
	}

	if filter == nil {
		filter = &table.PokemonFilter{}
	}

	filter.AddID(internal.Eq, obj.FkPokemon)
	result, err := par.PokemonRepository.FindAllPokemon(ctx, filter, nil)

	if err != nil {
		return nil, err
	}

	if result.TotalCount == 0 {
		return nil, nil
	}
	return &result.Data[0], nil
}
func (par *PokemonAbilitiesRltsRepository) AbilitiesByFkAbility(ctx context.Context, obj *table.PokemonAbilities, filter *table.AbilitiesFilter) (*table.Abilities, error) {
	if obj == nil {
		return nil, nil
	}

	if filter == nil {
		filter = &table.AbilitiesFilter{}
	}

	filter.AddID(internal.Eq, obj.FkAbility)
	result, err := par.AbilitiesRepository.FindAllAbilities(ctx, filter, nil)

	if err != nil {
		return nil, err
	}

	if result.TotalCount == 0 {
		return nil, nil
	}
	return &result.Data[0], nil
}
