// Code generated by sql2gql. DO NOT EDIT.

package sql2gql

import (
	"github.com/google/wire"
	"github.com/ketan-10/sql2gql/examples/pokemon/graphql/gen"
	"github.com/ketan-10/sql2gql/examples/pokemon/sql2gql/repo"
	"github.com/ketan-10/sql2gql/examples/pokemon/sql2gql/rlts"
)

type GoResolver struct {
	repo.IAbilitiesRepository
	rlts.IAbilitiesRltsRepository
	repo.IBaseStatsRepository
	rlts.IBaseStatsRltsRepository
	repo.IPokemonRepository
	rlts.IPokemonRltsRepository
	repo.IPokemonAbilitiesRepository
	rlts.IPokemonAbilitiesRltsRepository
	repo.IPokemonEvolutionRepository
	rlts.IPokemonEvolutionRltsRepository
	repo.IPokemonEvolutionMatchupRepository
	rlts.IPokemonEvolutionMatchupRltsRepository
	repo.IPokemonTypesRepository
	rlts.IPokemonTypesRltsRepository
	repo.ITypesRepository
	rlts.ITypesRltsRepository
}

//type IGoResolver interface {
//    Abilities() gen.AbilitiesResolver
//    BaseStats() gen.BaseStatsResolver
//    Pokemon() gen.PokemonResolver
//    PokemonAbilities() gen.PokemonAbilitiesResolver
//    PokemonEvolution() gen.PokemonEvolutionResolver
//    PokemonEvolutionMatchup() gen.PokemonEvolutionMatchupResolver
//    PokemonTypes() gen.PokemonTypesResolver
//    Types() gen.TypesResolver
//}

var NewGoResolver = wire.NewSet(
	wire.Struct(new(GoResolver), "*"),

// wire.Bind(new(IGoResolver), new(GoResolver)),
)

func (r *GoResolver) Abilities() gen.AbilitiesResolver {
	return r.IAbilitiesRltsRepository
}
func (r *GoResolver) BaseStats() gen.BaseStatsResolver {
	return r.IBaseStatsRltsRepository
}
func (r *GoResolver) Pokemon() gen.PokemonResolver {
	return r.IPokemonRltsRepository
}
func (r *GoResolver) PokemonAbilities() gen.PokemonAbilitiesResolver {
	return r.IPokemonAbilitiesRltsRepository
}
func (r *GoResolver) PokemonEvolution() gen.PokemonEvolutionResolver {
	return r.IPokemonEvolutionRltsRepository
}
func (r *GoResolver) PokemonEvolutionMatchup() gen.PokemonEvolutionMatchupResolver {
	return r.IPokemonEvolutionMatchupRltsRepository
}
func (r *GoResolver) PokemonTypes() gen.PokemonTypesResolver {
	return r.IPokemonTypesRltsRepository
}
func (r *GoResolver) Types() gen.TypesResolver {
	return r.ITypesRltsRepository
}
