// Code generated by sql2gql. DO NOT EDIT.

package sql2gql

import (
	"github.com/google/wire"
	"github.com/ketan-10/sql2gql/examples/pokemon/sql2gql/repo"
	"github.com/ketan-10/sql2gql/examples/pokemon/sql2gql/rlts"
)

var NewRepositorySet = wire.NewSet(

	repo.NewAbilitiesRepository,
	rlts.NewAbilitiesRltsRepository,
	repo.NewBaseStatsRepository,
	rlts.NewBaseStatsRltsRepository,
	repo.NewPokemonRepository,
	rlts.NewPokemonRltsRepository,
	repo.NewPokemonAbilitiesRepository,
	rlts.NewPokemonAbilitiesRltsRepository,
	repo.NewPokemonEvolutionRepository,
	rlts.NewPokemonEvolutionRltsRepository,
	repo.NewPokemonEvolutionMatchupRepository,
	rlts.NewPokemonEvolutionMatchupRltsRepository,
	repo.NewPokemonTypesRepository,
	rlts.NewPokemonTypesRltsRepository,
	repo.NewTypesRepository,
	rlts.NewTypesRltsRepository,
)
