# Code generated by mysql2graphql. DO NOT EDIT.

  {{ range .Enums}}
  {{- $name := joinWith "_" .Enum.TableName .Enum.ColumnName -}}
  {{ camelCase $name }}:
    model: ../mysql2gql/enum.{{ camelCase $name }}
  {{ end }}

  {{ range .Tables}}
  {{ camelCase .TableName }}:
    model: ../mysql2gql/table.{{ camelCase .TableName }}
  {{ camelCase .TableName }}Create:
    model: ../mysql2gql/table.{{ camelCase .TableName }}Create
  {{ camelCase .TableName }}Filter:
    model: ../mysql2gql/table.{{ camelCase .TableName }}Filter
  {{ camelCase .TableName }}Update:
    model: ../mysql2gql/table.{{ camelCase .TableName }}Update
  List{{ camelCase .TableName }}:
    model: ../mysql2gql/table.List{{ camelCase .TableName }}

{{ end }}
