# Code generated by sql2gql. DO NOT EDIT.

models:
  Pagination:
    model: ../internal.Pagination
  FilterOnField:
    model: ../internal.FilterOnField
  Datetime:
    model: ../internal.Datetime
  IntBool:
    model: ../internal.IntBool
  NullInt64:
    model: ../internal.NullInt64
  NullFloat64:
    model: ../internal.NullFloat64
  NullBool:
    model: ../internal.NullBool
  NullString:
    model: ../internal.NullString
  NullTime:
    model: ../internal.NullTime
  Map:
    model: ../internal.Map

  {{ range .Enums}}
  {{- $name := joinWith "_" .Enum.TableName .Enum.ColumnName -}}
  {{ camelCase $name }}:
    model: ../sql2gql/enum.{{ camelCase $name }}
  {{ end }}

  {{ range .Tables}}
  {{ camelCase .TableName }}:
    model: ../sql2gql/table.{{ camelCase .TableName }}
  {{ camelCase .TableName }}Create:
    model: ../sql2gql/table.{{ camelCase .TableName }}Create
  {{ camelCase .TableName }}Filter:
    model: ../sql2gql/table.{{ camelCase .TableName }}Filter
  {{ camelCase .TableName }}Update:
    model: ../sql2gql/table.{{ camelCase .TableName }}Update
  List{{ camelCase .TableName }}:
    model: ../sql2gql/table.List{{ camelCase .TableName }}

{{ end }}
