// Code generated by mysql2graphql. DO NOT EDIT.

package mysql2gql

import (
	"github.com/google/wire"
)

var NewRepositorySet = wire.NewSet(
    {{ range . }}
        repo.New{{ camelCase .Table.TableName }}Repository,
        rlts.New{{ camelCase .Table.TableName }}RltsRepository,
    {{- end }}
)
